# Generated by Django 4.2.23 on 2025-08-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'الصنف', 'verbose_name_plural': 'الصنف'},
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, 'توه'), (2, 'خلص'), (3, 'أجلناه'), (4, 'انلغى')], default=1),
        ),
    ]
